import json
import os

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# 🫀 3D Medical Image Segmentation with nnFormer (12 Swin-Transformer Encoder Blocks)\n",
                "### End-to-End Pipeline for ACDC Cardiac MRI & Synapse Multi-Organ CT\n",
                "\n",
                "This notebook provides a complete pipeline to prepare datasets, preprocess 3D volumes, train, and evaluate **nnFormer** on Kaggle GPUs (T4 / P100 / A100).\n",
                "\n",
                "#### Datasets & Paper-Specified Splits Included:\n",
                "1. **ACDC (Cardiac MRI)**: 100 Patients total $\\rightarrow$ **70 Training**, **10 Validation**, **20 Testing** (3 structures: RV, Myocardium, LV).\n",
                "2. **Synapse Multi-Organ (Abdominal CT)**: 30 Cases total $\\rightarrow$ **18 Training**, **12 Testing** (TransUNet split: 8 organs - aorta, gallbladder, spleen, left kidney, right kidney, liver, pancreas, stomach).\n",
                "\n",
                "> 💡 **Tip:** Enable GPU accelerator in Kaggle Notebook settings (**Settings -> Accelerator -> GPU T4 x2 or P100**)."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 1. Environment Configuration\n",
                "import os\n",
                "import sys\n",
                "import torch\n",
                "\n",
                "print('PyTorch Version:', torch.__version__)\n",
                "print('CUDA Available:', torch.cuda.is_available())\n",
                "if torch.cuda.is_available():\n",
                "    print('GPU Device Name:', torch.cuda.get_device_name(0))\n",
                "\n",
                "# Configure nnFormer Environment Paths & PYTHONPATH\n",
                "BASE_DIR = '/kaggle/working'\n",
                "PROJECT_DIR = os.path.join(BASE_DIR, 'nextgen-transformer')\n",
                "DATASET_DIR = os.path.join(BASE_DIR, 'DATASET')\n",
                "\n",
                "os.makedirs(PROJECT_DIR, exist_ok=True)\n",
                "os.environ['PYTHONPATH'] = PROJECT_DIR + ':' + os.environ.get('PYTHONPATH', '')\n",
                "os.environ['nnFormer_raw_data_base'] = os.path.join(DATASET_DIR, 'nnFormer_raw')\n",
                "os.environ['nnFormer_preprocessed'] = os.path.join(DATASET_DIR, 'nnFormer_preprocessed')\n",
                "os.environ['RESULTS_FOLDER'] = os.path.join(DATASET_DIR, 'nnFormer_trained_models')\n",
                "os.environ['nnFormer_def_n_proc'] = '2'\n",
                "os.environ['nnFormer_n_proc_DA'] = '1'\n",
                "os.environ['MAX_NUM_EPOCHS'] = '100'\n",
                "os.environ['NUM_BATCHES_PER_EPOCH'] = '10'\n",
                "os.environ['NUM_VAL_BATCHES_PER_EPOCH'] = '5'\n",
                "\n",
                "print('\\n--- Configured Paths ---')\n",
                "print('PYTHONPATH:', os.environ['PYTHONPATH'])\n",
                "print('nnFormer_raw_data_base:', os.environ['nnFormer_raw_data_base'])\n",
                "print('nnFormer_preprocessed:', os.environ['nnFormer_preprocessed'])\n",
                "print('RESULTS_FOLDER:', os.environ['RESULTS_FOLDER'])"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 2. Clone Fresh Repository & Install Dependencies\n",
                "%cd /kaggle/working\n",
                "import sys\n",
                "import os\n",
                "import numpy as np\n",
                "\n",
                "if np.__version__.startswith('2.'):\n",
                "    print('Updating NumPy to 1.x for C-ABI compatibility...')\n",
                "    !pip install -q \"numpy<2\" batchgenerators==0.23 SimpleITK nibabel timm einops medpy reportlab\n",
                "    print('Restarting Python kernel automatically...')\n",
                "    os._exit(0)\n",
                "\n",
                "!rm -rf /kaggle/working/nextgen-transformer\n",
                "!git clone https://github.com/sharadpawarsaini/nextgen-transformer.git /kaggle/working/nextgen-transformer\n",
                "%cd /kaggle/working/nextgen-transformer\n",
                "\n",
                "!pip install -q batchgenerators==0.23 SimpleITK nibabel timm einops medpy reportlab\n",
                "!pip install -e . --no-build-isolation\n",
                "\n",
                "PROJECT_DIR = '/kaggle/working/nextgen-transformer'\n",
                "if PROJECT_DIR not in sys.path:\n",
                "    sys.path.insert(0, PROJECT_DIR)\n",
                "\n",
                "print('✅ Repository cloned and dependencies installed successfully!')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 3. Dataset Setup: ACDC (70/10/20 Split) & Synapse (18/12 TransUNet Split)\n",
                "import subprocess\n",
                "\n",
                "print('Setting up ACDC (100 patients) and Synapse Multi-Organ (30 cases) datasets...')\n",
                "PROJECT_DIR = '/kaggle/working/nextgen-transformer'\n",
                "subprocess.run([sys.executable, 'prepare_full_acdc_synapse.py'], cwd=PROJECT_DIR, check=True)\n",
                "print('✅ Datasets generated and saved successfully!')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 4. Preprocessing: Task001_ACDC (Cardiac MRI) & Task002_Synapse (Abdominal CT)\n",
                "import os\n",
                "import sys\n",
                "import subprocess\n",
                "\n",
                "PROJECT_DIR = '/kaggle/working/nextgen-transformer'\n",
                "\n",
                "print('1. Preprocessing Task001_ACDC (Cardiac MRI)...')\n",
                "cmd_acdc = [sys.executable, '-m', 'nnformer.experiment_planning.nnFormer_plan_and_preprocess', '-t', '1', '-tl', '2', '-tf', '2', '--verify_dataset_integrity']\n",
                "subprocess.run(cmd_acdc, env=os.environ, cwd=PROJECT_DIR, check=True)\n",
                "\n",
                "print('2. Preprocessing Task002_Synapse (Abdominal CT)...')\n",
                "cmd_synapse = [sys.executable, '-m', 'nnformer.experiment_planning.nnFormer_plan_and_preprocess', '-t', '2', '-tl', '2', '-tf', '2', '--verify_dataset_integrity']\n",
                "subprocess.run(cmd_synapse, env=os.environ, cwd=PROJECT_DIR, check=True)\n",
                "\n",
                "print('✅ Preprocessing completed for both datasets!')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 5. Train nnFormer Models (12 Swin-Transformer Encoder Blocks)\n",
                "import os\n",
                "import sys\n",
                "import subprocess\n",
                "\n",
                "PROJECT_DIR = '/kaggle/working/nextgen-transformer'\n",
                "\n",
                "print('--- Training Task001_ACDC (Cardiac MRI - 12 Encoder Blocks) ---')\n",
                "cmd_acdc_train = [sys.executable, '-m', 'nnformer.run.run_training', '3d_fullres', 'nnFormerTrainerV2_nnformer_acdc', '1', '0']\n",
                "subprocess.run(cmd_acdc_train, env=os.environ, cwd=PROJECT_DIR, check=True)\n",
                "\n",
                "print('--- Training Task002_Synapse (Abdominal CT Multi-Organ - 12 Encoder Blocks) ---')\n",
                "cmd_synapse_train = [sys.executable, '-m', 'nnformer.run.run_training', '3d_fullres', 'nnFormerTrainerV2_nnformer_synapse', '2', '0']\n",
                "subprocess.run(cmd_synapse_train, env=os.environ, cwd=PROJECT_DIR, check=True)\n",
                "\n",
                "print('✅ Training completed for both ACDC and Synapse!')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 6. Perform Inference on Test Sets\n",
                "import os\n",
                "import sys\n",
                "import subprocess\n",
                "\n",
                "PROJECT_DIR = '/kaggle/working/nextgen-transformer'\n",
                "RAW_DATA = os.path.join(os.environ['nnFormer_raw_data_base'], 'nnFormer_raw_data')\n",
                "\n",
                "# 1. ACDC Test Inference\n",
                "acdc_task_dir = os.path.join(RAW_DATA, 'Task001_ACDC')\n",
                "acdc_out = os.path.join(acdc_task_dir, 'inferTs', 'nnformer_acdc')\n",
                "os.makedirs(acdc_out, exist_ok=True)\n",
                "cmd_acdc_infer = [sys.executable, '-m', 'nnformer.inference.predict_simple', '-i', os.path.join(acdc_task_dir, 'imagesTs'), '-o', acdc_out, '-m', '3d_fullres', '-t', '1', '-tr', 'nnFormerTrainerV2_nnformer_acdc', '-chk', 'model_final_checkpoint']\n",
                "subprocess.run(cmd_acdc_infer, env=os.environ, cwd=PROJECT_DIR, check=True)\n",
                "\n",
                "# 2. Synapse Test Inference\n",
                "synapse_task_dir = os.path.join(RAW_DATA, 'Task002_Synapse')\n",
                "synapse_out = os.path.join(synapse_task_dir, 'inferTs', 'nnformer_synapse')\n",
                "os.makedirs(synapse_out, exist_ok=True)\n",
                "cmd_synapse_infer = [sys.executable, '-m', 'nnformer.inference.predict_simple', '-i', os.path.join(synapse_task_dir, 'imagesTs'), '-o', synapse_out, '-m', '3d_fullres', '-t', '2', '-tr', 'nnFormerTrainerV2_nnformer_synapse', '-chk', 'model_final_checkpoint']\n",
                "subprocess.run(cmd_synapse_infer, env=os.environ, cwd=PROJECT_DIR, check=True)\n",
                "\n",
                "print('✅ Test inference complete for both ACDC and Synapse!')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 7. Calculate Dice Similarity Coefficient (DSC) Metrics\n",
                "import numpy as np\n",
                "import nibabel as nib\n",
                "\n",
                "def calculate_dice(pred, gt, class_id):\n",
                "    pred_c = (pred == class_id)\n",
                "    gt_c = (gt == class_id)\n",
                "    intersection = np.logical_and(pred_c, gt_c).sum()\n",
                "    denominator = pred_c.sum() + gt_c.sum()\n",
                "    if denominator == 0:\n",
                "        return 1.0\n",
                "    return (2.0 * intersection) / denominator\n",
                "\n",
                "RAW_DATA = os.path.join(os.environ['nnFormer_raw_data_base'], 'nnFormer_raw_data')\n",
                "\n",
                "# ACDC Evaluation\n",
                "acdc_pred_p = os.path.join(RAW_DATA, 'Task001_ACDC', 'inferTs', 'nnformer_acdc', 'patient081.nii.gz')\n",
                "acdc_gt_p = os.path.join(RAW_DATA, 'Task001_ACDC', 'labelsTs', 'patient081.nii.gz')\n",
                "if os.path.exists(acdc_pred_p) and os.path.exists(acdc_gt_p):\n",
                "    p = nib.load(acdc_pred_p).get_fdata()\n",
                "    g = nib.load(acdc_gt_p).get_fdata()\n",
                "    rv = calculate_dice(p, g, 1) * 100\n",
                "    myo = calculate_dice(p, g, 2) * 100\n",
                "    lv = calculate_dice(p, g, 3) * 100\n",
                "    mean_acdc = (rv + myo + lv) / 3.0\n",
                "    print('=' * 55)\n",
                "    print('       ACDC Cardiac MRI Evaluation Results (12 Blocks)')\n",
                "    print('=' * 55)\n",
                "    print(f'  Right Ventricle (RV) DSC : {rv:.2f}%')\n",
                "    print(f'  Myocardium (Myo) DSC     : {myo:.2f}%')\n",
                "    print(f'  Left Ventricle (LV) DSC  : {lv:.2f}%')\n",
                "    print('-' * 55)\n",
                "    print(f'  ACDC Mean Dice Score    : {mean_acdc:.2f}%')\n",
                "    print('=' * 55 + '\\n')\n",
                "\n",
                "# Synapse Evaluation\n",
                "syn_pred_p = os.path.join(RAW_DATA, 'Task002_Synapse', 'inferTs', 'nnformer_synapse', 'case0019.nii.gz')\n",
                "syn_gt_p = os.path.join(RAW_DATA, 'Task002_Synapse', 'labelsTs', 'case0019.nii.gz')\n",
                "if os.path.exists(syn_pred_p) and os.path.exists(syn_gt_p):\n",
                "    p = nib.load(syn_pred_p).get_fdata()\n",
                "    g = nib.load(syn_gt_p).get_fdata()\n",
                "    organs = ['Aorta', 'Gallbladder', 'Spleen', 'Left Kidney', 'Right Kidney', 'Liver', 'Pancreas', 'Stomach']\n",
                "    scores = []\n",
                "    print('=' * 55)\n",
                "    print('   Synapse Multi-Organ CT Evaluation Results (12 Blocks)')\n",
                "    print('=' * 55)\n",
                "    for idx, organ in enumerate(organs, start=1):\n",
                "        score = calculate_dice(p, g, idx) * 100\n",
                "        scores.append(score)\n",
                "        print(f'  {organ:<20} DSC : {score:.2f}%')\n",
                "    mean_syn = sum(scores) / len(scores)\n",
                "    print('-' * 55)\n",
                "    print(f'  Synapse 8-Organ Mean Dice : {mean_syn:.2f}%')\n",
                "    print('=' * 55)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 8. Visualizing Results (ACDC Cardiac MRI & Synapse Multi-Organ CT)\n",
                "import matplotlib.pyplot as plt\n",
                "import nibabel as nib\n",
                "\n",
                "RAW_DATA = os.path.join(os.environ['nnFormer_raw_data_base'], 'nnFormer_raw_data')\n",
                "\n",
                "# Plot ACDC Slice\n",
                "acdc_img = nib.load(os.path.join(RAW_DATA, 'Task001_ACDC', 'imagesTs', 'patient081_0000.nii.gz')).get_fdata()\n",
                "acdc_gt = nib.load(os.path.join(RAW_DATA, 'Task001_ACDC', 'labelsTs', 'patient081.nii.gz')).get_fdata()\n",
                "acdc_pred = nib.load(os.path.join(RAW_DATA, 'Task001_ACDC', 'inferTs', 'nnformer_acdc', 'patient081.nii.gz')).get_fdata()\n",
                "s_idx = acdc_img.shape[0] // 2\n",
                "\n",
                "fig, axes = plt.subplots(1, 3, figsize=(15, 5))\n",
                "axes[0].imshow(acdc_img[s_idx], cmap='gray'); axes[0].set_title('ACDC Input MRI Slice'); axes[0].axis('off')\n",
                "axes[1].imshow(acdc_gt[s_idx], cmap='jet'); axes[1].set_title('ACDC Ground Truth'); axes[1].axis('off')\n",
                "axes[2].imshow(acdc_pred[s_idx], cmap='jet'); axes[2].set_title('nnFormer ACDC Prediction'); axes[2].axis('off')\n",
                "plt.tight_layout(); plt.show()\n",
                "\n",
                "# Plot Synapse Slice\n",
                "syn_img = nib.load(os.path.join(RAW_DATA, 'Task002_Synapse', 'imagesTs', 'case0019_0000.nii.gz')).get_fdata()\n",
                "syn_gt = nib.load(os.path.join(RAW_DATA, 'Task002_Synapse', 'labelsTs', 'case0019.nii.gz')).get_fdata()\n",
                "syn_pred = nib.load(os.path.join(RAW_DATA, 'Task002_Synapse', 'inferTs', 'nnformer_synapse', 'case0019.nii.gz')).get_fdata()\n",
                "s_idx_syn = syn_img.shape[0] // 2\n",
                "\n",
                "fig, axes = plt.subplots(1, 3, figsize=(15, 5))\n",
                "axes[0].imshow(syn_img[s_idx_syn], cmap='gray'); axes[0].set_title('Synapse Input CT Slice'); axes[0].axis('off')\n",
                "axes[1].imshow(syn_gt[s_idx_syn], cmap='jet'); axes[1].set_title('Synapse Ground Truth'); axes[1].axis('off')\n",
                "axes[2].imshow(syn_pred[s_idx_syn], cmap='jet'); axes[2].set_title('nnFormer Synapse Prediction'); axes[2].axis('off')\n",
                "plt.tight_layout(); plt.show()"
            ]
        }
    ],
    "metadata": {
        "language_info": {
            "name": "python"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

out_path = r"c:\Users\shara\Desktop\nnFormer\nnFormer_Kaggle_Notebook.ipynb"
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2)

print(f"Notebook regenerated successfully at: {out_path}")
