import json
import os

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# 🫀 3D Medical Image Segmentation with nnFormer (12 Swin-Transformer Encoder Blocks)\n",
                "### End-to-End Pipeline for ACDC Cardiac MRI & Synapse Multi-Organ CT\n",
                "\n",
                "This notebook provides a complete pipeline to prepare datasets, preprocess 3D volumes, train, and evaluate **nnFormer** on Kaggle GPUs (T4 / P100 / A100).\n",
                "\n",
                "#### Datasets & Paper-Specified Splits Included:\n",
                "1. **ACDC (Cardiac MRI)**: 100 Patients total $\\rightarrow$ **70 Training**, **10 Validation**, **20 Testing** (3 structures: RV, Myocardium, LV).\n",
                "2. **Synapse Multi-Organ (Abdominal CT)**: 30 Cases total $\\rightarrow$ **18 Training**, **12 Testing** (TransUNet split: 8 organs - aorta, gallbladder, spleen, left kidney, right kidney, liver, pancreas, stomach).\n",
                "\n",
                "> 💡 **Tip:** Enable GPU accelerator in Kaggle Notebook settings (**Settings -> Accelerator -> GPU T4 x2 or P100**)."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 1. Environment Configuration\n",
                "import os\n",
                "import sys\n",
                "import torch\n",
                "\n",
                "print('PyTorch Version:', torch.__version__)\n",
                "print('CUDA Available:', torch.cuda.is_available())\n",
                "if torch.cuda.is_available():\n",
                "    print('GPU Device Name:', torch.cuda.get_device_name(0))\n",
                "\n",
                "# Configure nnFormer Environment Paths & PYTHONPATH\n",
                "BASE_DIR = '/kaggle/working'\n",
                "PROJECT_DIR = os.path.join(BASE_DIR, 'nextgen-transformer')\n",
                "DATASET_DIR = os.path.join(BASE_DIR, 'DATASET')\n",
                "\n",
                "os.makedirs(PROJECT_DIR, exist_ok=True)\n",
                "os.environ['PYTHONPATH'] = PROJECT_DIR + ':' + os.environ.get('PYTHONPATH', '')\n",
                "os.environ['nnFormer_raw_data_base'] = os.path.join(DATASET_DIR, 'nnFormer_raw')\n",
                "os.environ['nnFormer_preprocessed'] = os.path.join(DATASET_DIR, 'nnFormer_preprocessed')\n",
                "os.environ['RESULTS_FOLDER'] = os.path.join(DATASET_DIR, 'nnFormer_trained_models')\n",
                "os.environ['nnFormer_def_n_proc'] = '2'\n",
                "os.environ['nnFormer_n_proc_DA'] = '1'\n",
                "os.environ['MAX_NUM_EPOCHS'] = '250'\n",
                "os.environ['NUM_BATCHES_PER_EPOCH'] = '250'\n",
                "os.environ['NUM_VAL_BATCHES_PER_EPOCH'] = '50'\n",
                "\n",
                "print('\\n--- Configured Paths ---')\n",
                "print('PYTHONPATH:', os.environ['PYTHONPATH'])\n",
                "print('nnFormer_raw_data_base:', os.environ['nnFormer_raw_data_base'])\n",
                "print('nnFormer_preprocessed:', os.environ['nnFormer_preprocessed'])\n",
                "print('RESULTS_FOLDER:', os.environ['RESULTS_FOLDER'])"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 2. Clone Fresh Repository & Install Dependencies\n",
                "%cd /kaggle/working\n",
                "import sys\n",
                "import os\n",
                "import numpy as np\n",
                "\n",
                "if np.__version__.startswith('2.'):\n",
                "    print('Updating NumPy to 1.x for C-ABI compatibility...')\n",
                "    !pip install -q \"numpy<2\" batchgenerators==0.23 SimpleITK nibabel timm einops medpy reportlab\n",
                "    print('Restarting Python kernel automatically...')\n",
                "    os._exit(0)\n",
                "\n",
                "!rm -rf /kaggle/working/nextgen-transformer\n",
                "!git clone https://github.com/sharadpawarsaini/nextgen-transformer.git /kaggle/working/nextgen-transformer\n",
                "%cd /kaggle/working/nextgen-transformer\n",
                "\n",
                "!pip install -q batchgenerators==0.23 SimpleITK nibabel timm einops medpy reportlab\n",
                "!pip install -e . --no-build-isolation\n",
                "\n",
                "PROJECT_DIR = '/kaggle/working/nextgen-transformer'\n",
                "if PROJECT_DIR not in sys.path:\n",
                "    sys.path.insert(0, PROJECT_DIR)\n",
                "\n",
                "print('✅ Repository cloned and dependencies installed successfully!')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 3. Smart Dataset Setup: Auto-Detect Real Data in /kaggle/input/ or Generate Prepared Data\n",
                "import os\n",
                "import sys\n",
                "import shutil\n",
                "import subprocess\n",
                "\n",
                "RAW_DATA = os.path.join(os.environ['nnFormer_raw_data_base'], 'nnFormer_raw_data')\n",
                "os.makedirs(RAW_DATA, exist_ok=True)\n",
                "\n",
                "print('=== Setting up ACDC & Synapse Datasets ===')\n",
                "\n",
                "# --- 1. ACDC DATASET ---\n",
                "acdc_target = os.path.join(RAW_DATA, 'Task001_ACDC')\n",
                "acdc_input_options = [\n",
                "    '/kaggle/input/acdc-dataset',\n",
                "    '/kaggle/input/acdc-dataset-2017',\n",
                "    '/kaggle/input/acdc-2017'\n",
                "]\n",
                "real_acdc_found = False\n",
                "for option in acdc_input_options:\n",
                "    if os.path.exists(option):\n",
                "        print(f'Found Real ACDC Dataset in {option}!')\n",
                "        if os.path.exists(acdc_target): shutil.rmtree(acdc_target)\n",
                "        shutil.copytree(option, acdc_target)\n",
                "        real_acdc_found = True\n",
                "        print('✅ Real ACDC Dataset successfully loaded into Task001_ACDC!')\n",
                "        break\n",
                "\n",
                "if not real_acdc_found:\n",
                "    print('ℹ️ Real ACDC dataset not found in /kaggle/input/. Using prepared dataset builder...')\n",
                "\n",
                "# --- 2. SYNAPSE DATASET ---\n",
                "synapse_target = os.path.join(RAW_DATA, 'Task002_Synapse')\n",
                "synapse_input_options = [\n",
                "    '/kaggle/input/synapse-multi-organ-segmentation',\n",
                "    '/kaggle/input/synapse-ct-dataset',\n",
                "    '/kaggle/input/synapse-raw'\n",
                "]\n",
                "real_synapse_found = False\n",
                "for option in synapse_input_options:\n",
                "    if os.path.exists(option):\n",
                "        print(f'Found Real Synapse Dataset in {option}!')\n",
                "        if os.path.exists(synapse_target): shutil.rmtree(synapse_target)\n",
                "        shutil.copytree(option, synapse_target)\n",
                "        real_synapse_found = True\n",
                "        print('✅ Real Synapse Dataset successfully loaded into Task002_Synapse!')\n",
                "        break\n",
                "\n",
                "if not real_synapse_found:\n",
                "    print('ℹ️ Real Synapse dataset not found in /kaggle/input/. Using prepared dataset builder...')\n",
                "\n",
                "# If either dataset was not found in /kaggle/input/, run prepare_full_acdc_synapse.py\n",
                "if not (real_acdc_found and real_synapse_found):\n",
                "    PROJECT_DIR = '/kaggle/working/nextgen-transformer'\n",
                "    subprocess.run([sys.executable, 'prepare_full_acdc_synapse.py'], cwd=PROJECT_DIR, check=True)\n",
                "\n",
                "print('✅ Both ACDC and Synapse datasets are ready for 3D preprocessing & training!')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 4. Preprocessing: Task001_ACDC (Cardiac MRI) & Task002_Synapse (Abdominal CT)\n",
                "import os\n",
                "import sys\n",
                "import subprocess\n",
                "\n",
                "PROJECT_DIR = '/kaggle/working/nextgen-transformer'\n",
                "\n",
                "print('1. Preprocessing Task001_ACDC (Cardiac MRI)...')\n",
                "cmd_acdc = [sys.executable, '-m', 'nnformer.experiment_planning.nnFormer_plan_and_preprocess', '-t', '1', '-tl', '2', '-tf', '2']\n",
                "subprocess.run(cmd_acdc, env=os.environ, cwd=PROJECT_DIR, check=True)\n",
                "\n",
                "print('2. Preprocessing Task002_Synapse (Abdominal CT)...')\n",
                "cmd_synapse = [sys.executable, '-m', 'nnformer.experiment_planning.nnFormer_plan_and_preprocess', '-t', '2', '-tl', '2', '-tf', '2']\n",
                "subprocess.run(cmd_synapse, env=os.environ, cwd=PROJECT_DIR, check=True)\n",
                "\n",
                "print('✅ Preprocessing completed for both datasets!')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 5. Train nnFormer Models (12 Swin-Transformer Encoder Blocks)\n",
                "import os\n",
                "import sys\n",
                "import subprocess\n",
                "\n",
                "PROJECT_DIR = '/kaggle/working/nextgen-transformer'\n",
                "\n",
                "print('--- Training Task001_ACDC (Cardiac MRI - 12 Encoder Blocks) ---')\n",
                "cmd_acdc_train = [sys.executable, '-m', 'nnformer.run.run_training', '3d_fullres', 'nnFormerTrainerV2_nnformer_acdc', '1', '0']\n",
                "subprocess.run(cmd_acdc_train, env=os.environ, cwd=PROJECT_DIR, check=True)\n",
                "\n",
                "print('--- Training Task002_Synapse (Abdominal CT Multi-Organ - 12 Encoder Blocks) ---')\n",
                "cmd_synapse_train = [sys.executable, '-m', 'nnformer.run.run_training', '3d_fullres', 'nnFormerTrainerV2_nnformer_synapse', '2', '0']\n",
                "subprocess.run(cmd_synapse_train, env=os.environ, cwd=PROJECT_DIR, check=True)\n",
                "\n",
                "print('✅ Training completed for both ACDC and Synapse!')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 6. Perform Inference on Test Sets\n",
                "import os\n",
                "import sys\n",
                "import subprocess\n",
                "\n",
                "PROJECT_DIR = '/kaggle/working/nextgen-transformer'\n",
                "RAW_DATA = os.path.join(os.environ['nnFormer_raw_data_base'], 'nnFormer_raw_data')\n",
                "\n",
                "# 1. ACDC Test Inference\n",
                "acdc_task_dir = os.path.join(RAW_DATA, 'Task001_ACDC')\n",
                "acdc_out = os.path.join(acdc_task_dir, 'inferTs', 'nnformer_acdc')\n",
                "os.makedirs(acdc_out, exist_ok=True)\n",
                "cmd_acdc_infer = [sys.executable, '-m', 'nnformer.inference.predict_simple', '-i', os.path.join(acdc_task_dir, 'imagesTs'), '-o', acdc_out, '-m', '3d_fullres', '-t', '1', '-tr', 'nnFormerTrainerV2_nnformer_acdc', '-chk', 'model_final_checkpoint']\n",
                "subprocess.run(cmd_acdc_infer, env=os.environ, cwd=PROJECT_DIR, check=True)\n",
                "\n",
                "# 2. Synapse Test Inference\n",
                "synapse_task_dir = os.path.join(RAW_DATA, 'Task002_Synapse')\n",
                "synapse_out = os.path.join(synapse_task_dir, 'inferTs', 'nnformer_synapse')\n",
                "os.makedirs(synapse_out, exist_ok=True)\n",
                "cmd_synapse_infer = [sys.executable, '-m', 'nnformer.inference.predict_simple', '-i', os.path.join(synapse_task_dir, 'imagesTs'), '-o', synapse_out, '-m', '3d_fullres', '-t', '2', '-tr', 'nnFormerTrainerV2_nnformer_synapse', '-chk', 'model_final_checkpoint']\n",
                "subprocess.run(cmd_synapse_infer, env=os.environ, cwd=PROJECT_DIR, check=True)\n",
                "\n",
                "print('✅ Test inference complete for both ACDC and Synapse!')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 7. Calculate Dice Similarity Coefficient (DSC) Metrics\n",
                "import os\n",
                "import glob\n",
                "import numpy as np\n",
                "import nibabel as nib\n",
                "\n",
                "def calculate_dice(pred, gt, class_id):\n",
                "    pred_c = (pred == class_id)\n",
                "    gt_c = (gt == class_id)\n",
                "    intersection = np.logical_and(pred_c, gt_c).sum()\n",
                "    denominator = pred_c.sum() + gt_c.sum()\n",
                "    if denominator == 0:\n",
                "        return 1.0\n",
                "    return (2.0 * intersection) / denominator\n",
                "\n",
                "RAW_DATA = os.path.join(os.environ['nnFormer_raw_data_base'], 'nnFormer_raw_data')\n",
                "\n",
                "# ========================================================\n",
                "# 🫀 1. ACDC CARDIAC MRI EVALUATION (20 TEST PATIENTS)\n",
                "# ========================================================\n",
                "acdc_infer_dir = os.path.join(RAW_DATA, 'Task001_ACDC', 'inferTs', 'nnformer_acdc')\n",
                "acdc_gt_dir = os.path.join(RAW_DATA, 'Task001_ACDC', 'labelsTs')\n",
                "acdc_test_files = sorted(glob.glob(os.path.join(acdc_gt_dir, '*.nii.gz')))\n",
                "\n",
                "if acdc_test_files:\n",
                "    rv_scores, myo_scores, lv_scores = [], [], []\n",
                "    for gt_path in acdc_test_files:\n",
                "        fname = os.path.basename(gt_path)\n",
                "        pred_path = os.path.join(acdc_infer_dir, fname)\n",
                "        if os.path.exists(pred_path):\n",
                "            p = nib.load(pred_path).get_fdata()\n",
                "            g = nib.load(gt_path).get_fdata()\n",
                "            rv_scores.append(calculate_dice(p, g, 1) * 100)\n",
                "            myo_scores.append(calculate_dice(p, g, 2) * 100)\n",
                "            lv_scores.append(calculate_dice(p, g, 3) * 100)\n",
                "    \n",
                "    if rv_scores:\n",
                "        mean_rv = np.mean(rv_scores)\n",
                "        mean_myo = np.mean(myo_scores)\n",
                "        mean_lv = np.mean(lv_scores)\n",
                "        acdc_overall_mean = (mean_rv + mean_myo + mean_lv) / 3.0\n",
                "        print('=' * 65)\n",
                "        print('       🫀 ACDC CARDIAC MRI EVALUATION RESULTS (12 BLOCKS)')\n",
                "        print('=' * 65)\n",
                "        print(f'  Right Ventricle (RV) Mean DSC : {mean_rv:.2f}%')\n",
                "        print(f'  Myocardium (Myo) Mean DSC     : {mean_myo:.2f}%')\n",
                "        print(f'  Left Ventricle (LV) Mean DSC  : {mean_lv:.2f}%')\n",
                "        print('-' * 65)\n",
                "        print(f'  🏆 ACDC OVERALL MEAN DICE ACCURACY : {acdc_overall_mean:.2f}%')\n",
                "        print('=' * 65 + '\\n\\n')\n",
                "\n",
                "# ========================================================\n",
                "# 🩺 2. SYNAPSE MULTI-ORGAN CT EVALUATION (12 TEST CASES)\n",
                "# ========================================================\n",
                "syn_infer_dir = os.path.join(RAW_DATA, 'Task002_Synapse', 'inferTs', 'nnformer_synapse')\n",
                "syn_gt_dir = os.path.join(RAW_DATA, 'Task002_Synapse', 'labelsTs')\n",
                "syn_test_files = sorted(glob.glob(os.path.join(syn_gt_dir, '*.nii.gz')))\n",
                "\n",
                "if syn_test_files:\n",
                "    organs = ['Aorta', 'Gallbladder', 'Spleen', 'Left Kidney', 'Right Kidney', 'Liver', 'Pancreas', 'Stomach']\n",
                "    organ_scores = {o: [] for o in organs}\n",
                "    for gt_path in syn_test_files:\n",
                "        fname = os.path.basename(gt_path)\n",
                "        pred_path = os.path.join(syn_infer_dir, fname)\n",
                "        if os.path.exists(pred_path):\n",
                "            p = nib.load(pred_path).get_fdata()\n",
                "            g = nib.load(gt_path).get_fdata()\n",
                "            for idx, organ in enumerate(organs, start=1):\n",
                "                organ_scores[organ].append(calculate_dice(p, g, idx) * 100)\n",
                "    \n",
                "    if organ_scores['Aorta']:\n",
                "        print('=' * 65)\n",
                "        print('   🩺 SYNAPSE MULTI-ORGAN CT EVALUATION RESULTS (12 BLOCKS)')\n",
                "        print('=' * 65)\n",
                "        organ_means = []\n",
                "        for organ in organs:\n",
                "            m_score = np.mean(organ_scores[organ])\n",
                "            organ_means.append(m_score)\n",
                "            print(f'  {organ:<22} Mean DSC : {m_score:.2f}%')\n",
                "        synapse_overall_mean = np.mean(organ_means)\n",
                "        print('-' * 65)\n",
                "        print(f'  🏆 SYNAPSE 8-ORGAN OVERALL MEAN DICE ACCURACY : {synapse_overall_mean:.2f}%')\n",
                "        print('=' * 65)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 8. Visualizing Results (ACDC Cardiac MRI & Synapse Multi-Organ CT)\n",
                "import matplotlib.pyplot as plt\n",
                "import nibabel as nib\n",
                "\n",
                "RAW_DATA = os.path.join(os.environ['nnFormer_raw_data_base'], 'nnFormer_raw_data')\n",
                "\n",
                "# Plot ACDC Slice\n",
                "acdc_img = nib.load(os.path.join(RAW_DATA, 'Task001_ACDC', 'imagesTs', 'patient081_0000.nii.gz')).get_fdata()\n",
                "acdc_gt = nib.load(os.path.join(RAW_DATA, 'Task001_ACDC', 'labelsTs', 'patient081.nii.gz')).get_fdata()\n",
                "acdc_pred = nib.load(os.path.join(RAW_DATA, 'Task001_ACDC', 'inferTs', 'nnformer_acdc', 'patient081.nii.gz')).get_fdata()\n",
                "s_idx = acdc_img.shape[0] // 2\n",
                "\n",
                "fig, axes = plt.subplots(1, 3, figsize=(15, 5))\n",
                "axes[0].imshow(acdc_img[s_idx], cmap='gray'); axes[0].set_title('ACDC Input MRI Slice'); axes[0].axis('off')\n",
                "axes[1].imshow(acdc_gt[s_idx], cmap='jet'); axes[1].set_title('ACDC Ground Truth'); axes[1].axis('off')\n",
                "axes[2].imshow(acdc_pred[s_idx], cmap='jet'); axes[2].set_title('nnFormer ACDC Prediction'); axes[2].axis('off')\n",
                "plt.tight_layout(); plt.show()\n",
                "\n",
                "# Plot Synapse Slice\n",
                "syn_img = nib.load(os.path.join(RAW_DATA, 'Task002_Synapse', 'imagesTs', 'case0019_0000.nii.gz')).get_fdata()\n",
                "syn_gt = nib.load(os.path.join(RAW_DATA, 'Task002_Synapse', 'labelsTs', 'case0019.nii.gz')).get_fdata()\n",
                "syn_pred = nib.load(os.path.join(RAW_DATA, 'Task002_Synapse', 'inferTs', 'nnformer_synapse', 'case0019.nii.gz')).get_fdata()\n",
                "s_idx_syn = syn_img.shape[0] // 2\n",
                "\n",
                "fig, axes = plt.subplots(1, 3, figsize=(15, 5))\n",
                "axes[0].imshow(syn_img[s_idx_syn], cmap='gray'); axes[0].set_title('Synapse Input CT Slice'); axes[0].axis('off')\n",
                "axes[1].imshow(syn_gt[s_idx_syn], cmap='jet'); axes[1].set_title('Synapse Ground Truth'); axes[1].axis('off')\n",
                "axes[2].imshow(syn_pred[s_idx_syn], cmap='jet'); axes[2].set_title('nnFormer Synapse Prediction'); axes[2].axis('off')\n",
                "plt.tight_layout(); plt.show()"
            ]
        }
    ],
    "metadata": {
        "language_info": {
            "name": "python"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

out_path = r"c:\Users\shara\Desktop\nnFormer\nnFormer_Kaggle_Notebook.ipynb"
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2)

print(f"Notebook regenerated successfully at: {out_path}")
